# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_practice_project',
                'doc_host': 'https://vikas972.github.io',
                'git_url': 'https://github.com/vikas972/nbdev_practice_project',
                'lib_path': 'nbdev_practice_project'},
  'syms': {'nbdev_practice_project.core': {'nbdev_practice_project.core.foo': ('core.html#foo', 'nbdev_practice_project/core.py')}}}
