# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_practice_project',
                'doc_host': 'https://vikas972.github.io',
                'git_url': 'https://github.com/vikas972/nbdev_practice_project',
                'lib_path': 'nbdev_practice_project'},
  'syms': { 'nbdev_practice_project.dp': { 'nbdev_practice_project.dp.fact': ('dp.html#fact', 'nbdev_practice_project/dp.py'),
                                           'nbdev_practice_project.dp.fibo': ('dp.html#fibo', 'nbdev_practice_project/dp.py')},
            'nbdev_practice_project.intro': {'nbdev_practice_project.intro.add': ('intro.html#add', 'nbdev_practice_project/intro.py')}}}
