# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dp.ipynb.

# %% auto 0
__all__ = ['fibo', 'fact']

# %% ../nbs/01_dp.ipynb 3
def fibo(n):
    if n<0:
        return 0
    if n==0 or n==1:
        return n
    return fibo(n-1)+fibo(n-2)

# %% ../nbs/01_dp.ipynb 5
def fact(n):
    if n==1:
        return 1
    return fact(n-1)*n
