# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_intro.ipynb.

# %% auto 0
__all__ = ['add']

# %% ../nbs/00_intro.ipynb 3
def add(a,b):
    "This will add 2 integer numbers"
    print(f"The Addition of a and b is:{a+b}")
